# Generated by Django 5.0rc1 on 2023-11-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
