# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Outer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('inner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inner')),
            ],
        ),
        migrations.AddField(
            model_name='inner',
            name='nested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nested'),
        ),
    ]
